### ISSUE TITLE
Make Starts Singular

### ISSUE THREAD

**Issue by mhcrocker** [NSCC-ITC-Winter2024-ICOM5015-701-MCr/icom5015-ai-2024#13]
Change "starts" to "start" in the sentence "This command will starts up the docker containers that are used by FarmData2." in the "Starting FarmData2" section of `INSTALL.md.`

**Comment by labrocadabro** [comment]
I would like to work on this please!

**Comment by labrocadabro** [comment]
I would like to work on this please!
